### PR TITLE
refactor: use echarts types

### LINKED ISSUE #31: refactor: use @types/echarts
#### Feature Request

Make use of [@types/echarts](https://www.npmjs.com/package/@types/echarts)

#### What is the expected behavior?

`Echarts` API should be strongly typed

#### What is the motivation / use case for changing the behavior?

Compile-time type inference

### PR DESCRIPTION
**Pull request by jotatoledo**
Consume `@types/echarts` in the code base. Closes #31 

### What's included?
- Deps. update
- Refactor of base chart comp
- Removal of unused imports

#### General Tests for Every PR

- [x] `npm run serve:prod` still works.
- [ ] `npm run tslint` passes.
- [x] `npm run stylelint` passes.
- [x] `npm test` passes and code coverage is not lower.
- [x] `npm run build:lib` still works.

### CODE REVIEW

**Comment by emoralesb05** [comment]
My only concerns is bundle size.. since the purpose of importing things separately was modularity and only use what you really need, will need to check out pros/cons since it doesnt seem like that bad (increase is around ~400kb in prod mode ) in general, but just want to make sure.

**Comment by jotatoledo** [comment]
I see, Ill revisit my changes in a while.

**Comment by jotatoledo** [comment]
@emoralesb05 ATM it seems that there is now way to selectively import "sections" of the library when using the `@types/echarts` package. Furthermore, the **prod build** step is broken aftert rebase, as elements from `echarts` used in the codebase arent included in the type def.

I think Ill leave the PR as it is....

**Comment by jotatoledo** [comment]
Indeed 😭
Anyways, Ill close the PR for now

**Pull request closed without merging**
